# .goreleaser.yml
project_name: aws-console

# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...

builds:
  - main: ./main.go

    # Binary name.
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    # Default is the name of the project directory.
    binary: aws-console

    flags:
      - -trimpath
      - -v

    ldflags:
      - -s -w
      # - -X {{.ModulePath}}/cmd.Version={{.Version}}

    # Custom flags templates.
    # Default is empty.
    # flags:
    # - -tags=dev
    #   - -v
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    
    goarch:
      - amd64
      - arm64
    
    ignore:
      - goos: windows
        goarch: arm64

    mod_timestamp: '{{ .CommitTimestamp }}'

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - artifacts: checksum
    args: ["-u", "10949267+jacobfg@users.noreply.github.com", "--output", "${signature}", "--detach-sign", "${artifact}"]

archives:
  - name_template: '{{ .ProjectName }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    # replacements:
    #   darwin: Darwin
    #   linux: Linux
    #   windows: Windows
    #   386: i386
    #   amd64: x86_64
    files:
      - LICENSE.md
      - README.md

release:
  # Note: it can only be one: either github, gitlab or gitea
  github:
    owner: jacobfg
    name: aws-console

  # You can change the name of the release.
  name_template: "{{.ProjectName}}-v{{.Version}}"
